export const BANGALORE_AREAS = [
  "Koramangala, Bangalore",
  "Indiranagar, Bangalore",
  "HSR Layout, Bangalore",
  "Whitefield, Bangalore",
  "Electronic City, Bangalore",
  "MG Road, Bangalore",
  "Hebbal, Bangalore",
  "Jayanagar, Bangalore",
  "Bannerghatta Road, Bangalore",
  "Marathahalli, Bangalore",
  "Sarjapur Road, Bangalore",
  "BTM Layout, Bangalore",
  "JP Nagar, Bangalore",
  "Malleshwaram, Bangalore",
  "Rajajinagar, Bangalore",
  "Yelahanka, Bangalore",
  "KR Puram, Bangalore",
  "Bellandur, Bangalore",
  "Domlur, Bangalore",
  "Silk Board, Bangalore",
  "Majestic (City Railway Station), Bangalore",
  "Kempegowda International Airport, Bangalore",
  "UB City, Bangalore",
  "Brigade Road, Bangalore",
  "Richmond Road, Bangalore",
  "Sadashivanagar, Bangalore",
  "RT Nagar, Bangalore",
  "Nagarbhavi, Bangalore",
  "Banashankari, Bangalore",
  "Vijayanagar, Bangalore",
  "Yeshwanthpur, Bangalore",
  "Kengeri, Bangalore",
  "RR Nagar, Bangalore",
  "Devanahalli, Bangalore",
  "Tumkur Road, Bangalore",
];
