export const MUMBAI_AREAS = [
  "Andheri West, Mumbai",
  "Andheri East, Mumbai",
  "Bandra West, Mumbai",
  "Bandra East, Mumbai",
  "Borivali West, Mumbai",
  "Borivali East, Mumbai",
  "Malad West, Mumbai",
  "Malad East, Mumbai",
  "Goregaon West, Mumbai",
  "Goregaon East, Mumbai",
  "Kandivali West, Mumbai",
  "Kandivali East, Mumbai",
  "Jogeshwari West, Mumbai",
  "Jogeshwari East, Mumbai",
  "Santacruz West, Mumbai",
  "Santacruz East, Mumbai",
  "Vile Parle West, Mumbai",
  "Vile Parle East, Mumbai",
  "Kurla, Mumbai",
  "Ghatkopar West, Mumbai",
  "Ghatkopar East, Mumbai",
  "Mulund West, Mumbai",
  "Mulund East, Mumbai",
  "Chembur, Mumbai",
  "Powai, Mumbai",
  "Vikhroli, Mumbai",
  "Dadar, Mumbai",
  "Worli, Mumbai",
  "Lower Parel, Mumbai",
  "Bandra Kurla Complex (BKC), Mumbai",
  "Colaba, Mumbai",
  "Fort, Mumbai",
  "Nariman Point, Mumbai",
  "Churchgate, Mumbai",
  "Chhatrapati Shivaji Maharaj International Airport, Mumbai",
  "Navi Mumbai International Airport (NMIA), Mumbai",
  "Vashi, Navi Mumbai",
  "Belapur CBD, Navi Mumbai",
  "Kharghar, Navi Mumbai",
  "Panvel, Navi Mumbai",
  "Nerul, Navi Mumbai",
  "Airoli, Navi Mumbai",
  "Kopar Khairane, Navi Mumbai",
  "Thane West, Thane",
  "Thane East, Thane",
  "Kalyan, Thane",
  "Dombivli, Thane",
  "Mira Road, Thane",
  "Vasai, Palghar",
  "Virar, Palghar",
];
